messaging:
  archiveHost: QMT13.jbhunt.com
  archivePort: 1414
  archiveQueueManager: QMT13
  archiveChannel: SI.CLIENT1
  errorHost: QMT13.JBHUNT.COM
  errorPort: 1414
  errorQueueManager: QMT13
  errorChannel: EDI.CLIENT1

  activeMq:
    username: admin
    password: admin
    brokerUrl: "failover:(tcp://localhost:61616)?randomize=false&jms.watchTopicAdvisories=false&jms.useAsyncSend=true&jms.prefetchPolicy.all=1&startupMaxReconnectAttempts=1"

  webMq:
    archive:
      queueName: EDI.Q.ARCHIVE.AZURE

    error:
      queueName: EDI.Q.ARCHIVE.AZURE.ERROR

  eventHub:
    namespaceName: jbh-ediarchive-eh-01-tst
    eventHubName: documentmetadata
    sasKeyName: Send-Listen

blobStorage:
  containerName: edi

cosmos:
  host: edi-mongo-dev.documents.azure.com:10255
  user: edi-mongo-dev
  database: EDIArchive_Unstructured_DEV
  collection: EDIDocumentMetadata
  retryMaxAttempt: 6
  backOffPeriod: 30000

GCP:
  bucket: "jsdc1ediarchive01"
  project: "jbh-dev-edi"

jbhunt:
  b2b:
    edidatasource:
      electronicdatainterchange:
          url: jdbc:sqlserver://ElectronicDataInterchange_TST.nonprod.jbhunt.com:1433;DatabaseName=ElectronicDataInterchange_TST;sendstringparametersasunicode=false;integratedSecurity=true
          jdbcurl: jdbc:sqlserver://ElectronicDataInterchange_TST.nonprod.jbhunt.com:1433;DatabaseName=ElectronicDataInterchange_TST;sendstringparametersasunicode=false;integratedSecurity=true

